const KEY = 'paytrack.v1';
const config = window.PAYTRACK_CONFIG || {};
const database = config.supabaseUrl&&config.supabaseAnonKey&&window.supabase?window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey):null;
const money = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const today = () => new Date().toISOString().slice(0,10);
let state = JSON.parse(localStorage.getItem(KEY)) || { invoices: [], transactions: [] }, selectedChaseFile=null;
document.querySelector('#driveFolder').href = config.driveFolderUrl || '#';
const id = () => crypto.randomUUID();
function invoiceFromRow(row){return {id:row.id,vendor:row.vendor,email:row.email,invoiceNo:row.invoice_no,amount:Number(row.amount),invoiceDate:row.invoice_date,dueDate:row.due_date,status:row.status,notes:row.notes,attachment:row.attachment_name,paymentId:row.payment_id,manualPaid:row.manual_paid,paidDate:row.paid_date};}
function transactionFromRow(row){return {id:row.id,date:row.transaction_date,description:row.description,amount:Number(row.amount),invoiceId:row.invoice_id,source:row.source,wireStatus:row.wire_status,review:row.review};}
function invoiceToRow(i){return {id:i.id,vendor:i.vendor,email:i.email,invoice_no:i.invoiceNo||null,amount:i.amount,invoice_date:i.invoiceDate||null,due_date:i.dueDate||null,status:i.status,notes:i.notes||null,attachment_name:i.attachment||null,payment_id:i.paymentId||null,manual_paid:!!i.manualPaid,paid_date:i.paidDate||null};}
function transactionToRow(t){return {id:t.id,transaction_date:t.date,description:t.description,amount:t.amount,invoice_id:t.invoiceId||null,source:t.source||null,wire_status:t.wireStatus||null,review:!!t.review};}
async function syncDatabase(){if(!database||!await currentSession())return;const [invoices,transactions]=await Promise.all([database.from('invoices').upsert(state.invoices.map(invoiceToRow)),database.from('transactions').upsert(state.transactions.map(transactionToRow))]);if(invoices.error)throw invoices.error;if(transactions.error)throw transactions.error;}
async function currentSession(){return database?(await database.auth.getSession()).data.session:null;}
async function loadDatabase(){if(!database||!await currentSession())return;const [invoices,transactions]=await Promise.all([database.from('invoices').select('*'),database.from('transactions').select('*')]);if(invoices.error||transactions.error)throw invoices.error||transactions.error;state={invoices:invoices.data.map(invoiceFromRow),transactions:transactions.data.map(transactionFromRow)};localStorage.setItem(KEY,JSON.stringify(state));render();}
function save(){ localStorage.setItem(KEY, JSON.stringify(state)); render();syncDatabase().catch(error=>{console.error('Database sync failed',error);document.querySelector('#importMessage').textContent='Saved on this device, but database sync failed. Check Supabase setup.';}); }
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function amount(v){return money.format(Number(v||0));}
function statusClass(s){return s.replace(' ',' ');}
function getMatches(){return state.invoices.filter(i=>i.status!=='Paid').flatMap(i=>state.transactions.filter(t=>!t.invoiceId&&t.wireStatus!=='Processing' && Math.abs(Math.abs(t.amount)-i.amount)<.01 && Math.abs(new Date(t.date)-new Date(i.invoiceDate||i.dueDate||today()))/(864e5)<=45).map(t=>({i,t})));}
function render(){
 const q=document.querySelector('#search').value.toLowerCase(), filter=document.querySelector('#statusFilter').value;
 const visible=state.invoices.filter(i=>(!filter||i.status===filter)&&[i.vendor,i.email,i.invoiceNo,i.amount].join(' ').toLowerCase().includes(q));
 document.querySelector('#invoiceRows').innerHTML=visible.length?visible.map(i=>`<tr><td><strong>${escapeHTML(i.invoiceNo||'No invoice #')}</strong><br><small>${i.invoiceDate||'No date'}</small></td><td>${escapeHTML(i.vendor)}<br><small>${escapeHTML(i.email)}</small></td><td>${amount(i.amount)}</td><td>${i.dueDate||'—'}</td><td><span class="status ${statusClass(i.status)}">${i.status}</span></td><td>${i.paymentId?'Chase linked':i.manualPaid?'Manual confirmation':'—'}</td><td class="row-actions">${i.status!=='Paid'?`<button class="small-btn" data-paid="${i.id}">Mark paid</button>`:''}<button class="small-btn" data-edit="${i.id}">View</button></td></tr>`).join(''):'<tr><td class="empty" colspan="7">No invoices found. Add one to start tracking.</td></tr>';
 const ledgerQuery=document.querySelector('#ledgerSearch')?.value.toLowerCase()||'',ledgerFilter=document.querySelector('#ledgerFilter')?.value||'',ledgerRows=state.transactions.filter(t=>{const inv=state.invoices.find(i=>i.id===t.invoiceId),ledgerState=inv?'Matched':t.wireStatus||'Unmatched';return (!ledgerFilter||ledgerState===ledgerFilter)&&[t.date,t.description,t.amount,ledgerState].join(' ').toLowerCase().includes(ledgerQuery)});document.querySelector('#transactionRows').innerHTML=ledgerRows.length?ledgerRows.map(t=>{let inv=state.invoices.find(i=>i.id===t.invoiceId);return `<tr><td>${t.date}</td><td>${escapeHTML(t.description)}</td><td>${amount(t.amount)}</td><td>${inv?'Matched':t.wireStatus==='Processing'?'Processing':t.wireStatus||'Unmatched'}</td><td>${inv?escapeHTML(inv.vendor+' · '+(inv.invoiceNo||'')):'—'}</td></tr>`}).join(''):'<tr><td class="empty" colspan="5">No payment-ledger entries match this view. Import a Chase PDF or CSV to add wires.</td></tr>';
 const matches=getMatches(); document.querySelector('#matchBadge').textContent=matches.length||'';
 document.querySelector('#matchList').innerHTML=matches.length?matches.map(({i,t})=>`<article class="match"><div><h3>${escapeHTML(i.vendor)} · ${amount(i.amount)}</h3><p>Possible match: ${t.date} — ${escapeHTML(t.description)}. This does not mark the invoice paid until you confirm.</p></div><div class="match-actions"><button class="secondary" data-dismiss="${i.id}:${t.id}">Not a match</button><button class="primary" data-confirm="${i.id}:${t.id}">Confirm paid</button></div></article>`).join(''):'<div class="empty">Nothing needs matching right now.</div>';
 const unpaid=state.invoices.filter(i=>i.status!=='Paid'), overdue=unpaid.filter(i=>i.dueDate&&i.dueDate<today()), paid=state.invoices.filter(i=>i.status==='Paid'&&i.paidDate?.slice(0,7)===today().slice(0,7));
 document.querySelector('#unpaidCount').textContent=unpaid.length;document.querySelector('#unpaidAmount').textContent=amount(unpaid.reduce((a,i)=>a+i.amount,0));document.querySelector('#overdueCount').textContent=overdue.length;document.querySelector('#overdueAmount').textContent=amount(overdue.reduce((a,i)=>a+i.amount,0));document.querySelector('#paidCount').textContent=paid.length;document.querySelector('#paidAmount').textContent=amount(paid.reduce((a,i)=>a+i.amount,0));document.querySelector('#reviewCount').textContent=matches.length;
}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(lines.length<2)return [];const rows=lines.map(l=>{let a=[],s='',q=false;for(let c of l+','){if(c==='"')q=!q;else if(c===','&&!q){a.push(s.trim());s='';}else s+=c;}return a;});const h=rows.shift().map(x=>x.toLowerCase());const at=(r,names)=>r[h.findIndex(x=>names.some(n=>x.includes(n)))];return rows.map(r=>{let raw=at(r,['amount','debit','credit'])||'';let debit=at(r,['debit amount']),credit=at(r,['credit amount']);let v=credit?Number(credit.replace(/[$,]/g,'')):debit?-Number(debit.replace(/[$,]/g,'')):Number(raw.replace(/[$,]/g,''));return {id:id(),date:at(r,['transaction date','posting date','date'])||today(),description:at(r,['description','memo','name'])||'Chase transaction',amount:v,invoiceId:null,source:'CSV'};}).filter(x=>x.amount);}
async function parsePDF(file){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/legacy/build/pdf.worker.mjs';const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let lines=[];for(let p=1;p<=pdf.numPages;p++){const items=(await (await pdf.getPage(p)).getTextContent()).items.filter(x=>x.str).sort((a,b)=>b.transform[5]-a.transform[5]||a.transform[4]-b.transform[4]);let grouped=[];for(const item of items){let line=grouped.find(x=>Math.abs(x.y-item.transform[5])<3);if(!line){line={y:item.transform[5],items:[]};grouped.push(line)}line.items.push(item)}lines.push(...grouped.map(x=>x.items.sort((a,b)=>a.transform[4]-b.transform[4]).map(x=>x.str).join(' ')))}const months={jan:'01',feb:'02',mar:'03',apr:'04',may:'05',jun:'06',jul:'07',aug:'08',sep:'09',oct:'10',nov:'11',dec:'12'};const row=/^([A-Z][a-z]{2})\s+(\d{1,2}),\s+(\d{4})\s+(Sent|Processing|Canceled|Failed)\s+(.+?)\s+(\d{8,})\s+(\$[\d,]+\.\d{2})/i;const candidates=lines.map(line=>{const match=line.match(row);if(!match)return null;const [,month,day,year,wireStatus,recipient,transactionNumber,rawAmount]=match;return {id:id(),date:`${year}-${months[month.toLowerCase()]}-${day.padStart(2,'0')}`,description:`Wire to ${recipient.trim()} · #${transactionNumber}`,amount:Number(rawAmount.replace(/[$,]/g,'')),invoiceId:null,source:'Chase PDF',wireStatus,review:true};}).filter(Boolean);if(!candidates.length){const error=new Error('NO_WIRE_ROWS');error.code='NO_WIRE_ROWS';throw error}return candidates;}
document.querySelector('#openInvoice').onclick=()=>document.querySelector('#invoiceDialog').showModal();
document.querySelectorAll('[data-close-invoice]').forEach(button=>button.onclick=()=>document.querySelector('#invoiceDialog').close());
document.querySelector('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.invoices.unshift({id:id(),vendor:f.get('vendor'),email:f.get('email'),invoiceNo:f.get('invoiceNo'),amount:Number(f.get('amount')),invoiceDate:f.get('invoiceDate'),dueDate:f.get('dueDate'),status:f.get('status'),notes:f.get('notes'),attachment:f.get('attachment')?.name||'',paymentId:null,manualPaid:false});e.target.reset();document.querySelector('#invoiceDialog').close();save();});
async function importChaseFile(){const file=selectedChaseFile,message=document.querySelector('#importMessage'),button=document.querySelector('#processChase');if(!file)return;button.disabled=true;message.textContent='Reading Chase statement…';try{const incoming=file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')?await parsePDF(file):parseCSV(await file.text());let added=0,updated=0;for(const candidate of incoming){const existing=state.transactions.find(t=>[t.date,t.amount,t.description].join('|')===[candidate.date,candidate.amount,candidate.description].join('|'));if(!existing){state.transactions.push(candidate);added++;}else if(existing.wireStatus==='Processing'&&candidate.wireStatus==='Sent'){Object.assign(existing,{...candidate,id:existing.id,invoiceId:existing.invoiceId});updated++;}}message.textContent=added||updated?`${added} transaction candidate(s) added${updated?`; ${updated} Processing wire(s) updated to Sent`:''}. Review before confirming payment.`:'No new transactions found. This statement may not contain new wire activity.';save();}catch(error){if(error?.name==='PasswordException')message.textContent='This Chase PDF is password-protected. Download an unprotected copy from Chase, then upload it again.';else if(error?.name==='InvalidPDFException')message.textContent='This file is not a readable PDF or the download is incomplete. Re-download it from Chase and try again.';else if(error?.code==='NO_WIRE_ROWS')message.textContent='The PDF opened, but no dated wire rows were found. It may be a scanned/image-only statement or a different Chase report.';else message.textContent=`PDF reader error: ${error?.message||'unknown error'}. Please reload the app and try the file again.`;}finally{selectedChaseFile=null;document.querySelector('#chaseUpload').value='';document.querySelector('#selectedFile').textContent='No file selected yet.';button.disabled=true;}};
document.querySelector('#chaseUpload').onchange=e=>{selectedChaseFile=e.target.files[0]||null;document.querySelector('#selectedFile').textContent=selectedChaseFile?`Selected: ${selectedChaseFile.name}`:'No file selected yet.';document.querySelector('#processChase').disabled=!selectedChaseFile;document.querySelector('#importMessage').textContent='';};
document.querySelector('#processChase').onclick=importChaseFile;
document.addEventListener('click',e=>{const paid=e.target.dataset.paid,edit=e.target.dataset.edit,confirm=e.target.dataset.confirm,dismiss=e.target.dataset.dismiss;if(paid){let i=state.invoices.find(x=>x.id===paid);i.status='Paid';i.manualPaid=true;i.paidDate=today();save();}if(edit){let i=state.invoices.find(x=>x.id===edit);alert(`${i.vendor}\n${i.invoiceNo||'No invoice number'}\n${amount(i.amount)}\nStatus: ${i.status}\n\n${i.notes||'No notes'}`)}if(confirm){const [ii,tt]=confirm.split(':');let i=state.invoices.find(x=>x.id===ii),t=state.transactions.find(x=>x.id===tt);i.status='Paid';i.paymentId=t.id;i.paidDate=t.date;t.invoiceId=i.id;save();}if(dismiss){const [ii,tt]=dismiss.split(':');let i=state.invoices.find(x=>x.id===ii),t=state.transactions.find(x=>x.id===tt);t.invoiceId='dismissed-'+i.id;save();}});
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active');});
document.querySelector('#search').oninput=render;document.querySelector('#statusFilter').onchange=render;document.querySelector('#ledgerSearch').oninput=render;document.querySelector('#ledgerFilter').onchange=render;
document.querySelector('#resetDemo').onclick=()=>{if(confirm('Reset all local tracker data?')){state={invoices:[],transactions:[]};save();}};
document.querySelector('#authButton').onclick=async()=>{if(!database){alert('Add your Supabase Project URL and anon key in config.js first.');return}const session=await currentSession();if(session){await database.auth.signOut();document.querySelector('#authButton').textContent='Connect database';return}const email=prompt('Enter your email for the private PayTrack sign-in link:');if(!email)return;const {error}=await database.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});alert(error?`Could not send sign-in link: ${error.message}`:'Check your email and open the PayTrack sign-in link.');};
document.querySelector('#driveConnectButton').onclick=async()=>{if(!database){alert('Connect the database first.');return}const session=await currentSession();if(!session){alert('Please sign in first using Connect database.');return}const button=document.querySelector('#driveConnectButton');button.disabled=true;button.textContent='Opening Google…';try{const response=await fetch(`${config.supabaseUrl}/functions/v1/${config.driveConnectFunction}`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,apikey:config.supabaseAnonKey}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not start Google Drive connection.');location.assign(data.authorizationUrl)}catch(error){alert(error.message||'Could not connect Google Drive.');button.disabled=false;button.textContent='Connect Google Drive';}};
render();
currentSession().then(session=>{if(session)document.querySelector('#authButton').textContent='Sign out';if(new URLSearchParams(location.search).get('drive')==='connected')alert('Google Drive connected. New PDFs will appear after the scheduled sync is enabled.');if(new URLSearchParams(location.search).get('drive')==='failed')alert('Google Drive connection was not completed. Please try again.');return loadDatabase();}).catch(()=>{});
loadDatabase().catch(error=>{console.error('Database load failed',error);document.querySelector('#importMessage').textContent='Database connection needs setup. Your existing local data is still available on this device.';});
