const KEY = 'paytrack.v1';
const config = window.PAYTRACK_CONFIG || {};
const money = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const today = () => new Date().toISOString().slice(0,10);
let state = JSON.parse(localStorage.getItem(KEY)) || { invoices: [], transactions: [] };
document.querySelector('#driveFolder').href = config.driveFolderUrl || '#';
const id = () => crypto.randomUUID();
function save(){ localStorage.setItem(KEY, JSON.stringify(state)); render(); }
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function amount(v){return money.format(Number(v||0));}
function statusClass(s){return s.replace(' ',' ');}
function getMatches(){return state.invoices.filter(i=>i.status!=='Paid').flatMap(i=>state.transactions.filter(t=>!t.invoiceId && Math.abs(Math.abs(t.amount)-i.amount)<.01 && Math.abs(new Date(t.date)-new Date(i.invoiceDate||i.dueDate||today()))/(864e5)<=45).map(t=>({i,t})));}
function render(){
 const q=document.querySelector('#search').value.toLowerCase(), filter=document.querySelector('#statusFilter').value;
 const visible=state.invoices.filter(i=>(!filter||i.status===filter)&&[i.vendor,i.email,i.invoiceNo,i.amount].join(' ').toLowerCase().includes(q));
 document.querySelector('#invoiceRows').innerHTML=visible.length?visible.map(i=>`<tr><td><strong>${escapeHTML(i.invoiceNo||'No invoice #')}</strong><br><small>${i.invoiceDate||'No date'}</small></td><td>${escapeHTML(i.vendor)}<br><small>${escapeHTML(i.email)}</small></td><td>${amount(i.amount)}</td><td>${i.dueDate||'—'}</td><td><span class="status ${statusClass(i.status)}">${i.status}</span></td><td>${i.paymentId?'Chase linked':i.manualPaid?'Manual confirmation':'—'}</td><td class="row-actions">${i.status!=='Paid'?`<button class="small-btn" data-paid="${i.id}">Mark paid</button>`:''}<button class="small-btn" data-edit="${i.id}">View</button></td></tr>`).join(''):'<tr><td class="empty" colspan="7">No invoices found. Add one to start tracking.</td></tr>';
 document.querySelector('#transactionRows').innerHTML=state.transactions.length?state.transactions.map(t=>{let inv=state.invoices.find(i=>i.id===t.invoiceId);return `<tr><td>${t.date}</td><td>${escapeHTML(t.description)}</td><td>${amount(t.amount)}</td><td>${inv?'Matched':'Unmatched'}</td><td>${inv?escapeHTML(inv.vendor+' · '+(inv.invoiceNo||'')):'—'}</td></tr>`}).join(''):'<tr><td class="empty" colspan="5">Upload a Chase CSV to create your payment ledger.</td></tr>';
 const matches=getMatches(); document.querySelector('#matchBadge').textContent=matches.length||'';
 document.querySelector('#matchList').innerHTML=matches.length?matches.map(({i,t})=>`<article class="match"><div><h3>${escapeHTML(i.vendor)} · ${amount(i.amount)}</h3><p>Possible match: ${t.date} — ${escapeHTML(t.description)}. This does not mark the invoice paid until you confirm.</p></div><div class="match-actions"><button class="secondary" data-dismiss="${i.id}:${t.id}">Not a match</button><button class="primary" data-confirm="${i.id}:${t.id}">Confirm paid</button></div></article>`).join(''):'<div class="empty">Nothing needs matching right now.</div>';
 const unpaid=state.invoices.filter(i=>i.status!=='Paid'), overdue=unpaid.filter(i=>i.dueDate&&i.dueDate<today()), paid=state.invoices.filter(i=>i.status==='Paid'&&i.paidDate?.slice(0,7)===today().slice(0,7));
 document.querySelector('#unpaidCount').textContent=unpaid.length;document.querySelector('#unpaidAmount').textContent=amount(unpaid.reduce((a,i)=>a+i.amount,0));document.querySelector('#overdueCount').textContent=overdue.length;document.querySelector('#overdueAmount').textContent=amount(overdue.reduce((a,i)=>a+i.amount,0));document.querySelector('#paidCount').textContent=paid.length;document.querySelector('#paidAmount').textContent=amount(paid.reduce((a,i)=>a+i.amount,0));document.querySelector('#reviewCount').textContent=matches.length;
}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(lines.length<2)return [];const rows=lines.map(l=>{let a=[],s='',q=false;for(let c of l+','){if(c==='"')q=!q;else if(c===','&&!q){a.push(s.trim());s='';}else s+=c;}return a;});const h=rows.shift().map(x=>x.toLowerCase());const at=(r,names)=>r[h.findIndex(x=>names.some(n=>x.includes(n)))];return rows.map(r=>{let raw=at(r,['amount','debit','credit'])||'';let debit=at(r,['debit amount']),credit=at(r,['credit amount']);let v=credit?Number(credit.replace(/[$,]/g,'')):debit?-Number(debit.replace(/[$,]/g,'')):Number(raw.replace(/[$,]/g,''));return {id:id(),date:at(r,['transaction date','posting date','date'])||today(),description:at(r,['description','memo','name'])||'Chase transaction',amount:v,invoiceId:null};}).filter(x=>x.amount);}
document.querySelector('#openInvoice').onclick=()=>document.querySelector('#invoiceDialog').showModal();
document.querySelector('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.invoices.unshift({id:id(),vendor:f.get('vendor'),email:f.get('email'),invoiceNo:f.get('invoiceNo'),amount:Number(f.get('amount')),invoiceDate:f.get('invoiceDate'),dueDate:f.get('dueDate'),status:f.get('status'),notes:f.get('notes'),attachment:f.get('attachment')?.name||'',paymentId:null,manualPaid:false});e.target.reset();document.querySelector('#invoiceDialog').close();save();});
document.querySelector('#chaseUpload').onchange=async e=>{const file=e.target.files[0];if(!file)return;const incoming=parseCSV(await file.text());const seen=new Set(state.transactions.map(t=>[t.date,t.amount,t.description].join('|')));state.transactions.push(...incoming.filter(t=>!seen.has([t.date,t.amount,t.description].join('|'))));e.target.value='';save();};
document.addEventListener('click',e=>{const paid=e.target.dataset.paid,edit=e.target.dataset.edit,confirm=e.target.dataset.confirm,dismiss=e.target.dataset.dismiss;if(paid){let i=state.invoices.find(x=>x.id===paid);i.status='Paid';i.manualPaid=true;i.paidDate=today();save();}if(edit){let i=state.invoices.find(x=>x.id===edit);alert(`${i.vendor}\n${i.invoiceNo||'No invoice number'}\n${amount(i.amount)}\nStatus: ${i.status}\n\n${i.notes||'No notes'}`)}if(confirm){const [ii,tt]=confirm.split(':');let i=state.invoices.find(x=>x.id===ii),t=state.transactions.find(x=>x.id===tt);i.status='Paid';i.paymentId=t.id;i.paidDate=t.date;t.invoiceId=i.id;save();}if(dismiss){const [ii,tt]=dismiss.split(':');let i=state.invoices.find(x=>x.id===ii),t=state.transactions.find(x=>x.id===tt);t.invoiceId='dismissed-'+i.id;save();}});
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active');});
document.querySelector('#search').oninput=render;document.querySelector('#statusFilter').onchange=render;
document.querySelector('#resetDemo').onclick=()=>{if(confirm('Reset all local tracker data?')){state={invoices:[],transactions:[]};save();}};
render();
